/*
 * Copyright (c) 2019 simplity.org
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.simplity.fm.form;

import org.simplity.fm.rdb.DbParam;

/**
 * @author simplity.org
 *
 */
public class DbMetaData {
	/**
	 * e.g. where a=? and b=?
	 */
	public String whereClause;
	/**
	 * db parameters to be used for the where clause
	 */
	public DbParam[] whereParams;
	/**
	 * e.g. select a,b,c from t
	 */
	public String selectClause;
	/**
	 * db parameters to be used to receive data from the result set of the slect query
	 */
	public DbParam[] selectParams;
	/**
	 * e.g insert a,b,c,d into table1 values(?,?,?,?) 
	 */
	public String insertClause;
	/**
	 * db parameters for the insert sql 
	 */
	public DbParam[] insertParams;
	
	/**
	 * e.g. update table1 set a=?, b=?, c=?
	 */
	public String updateClause;
	/**
	 * db parameters for the update sql
	 */
	public DbParam[] updateParams;
	
	/**
	 * e.g. delete from table1. Note that where is not part of this.
	 */
	public String deleteClause;
	
	/**
	 * true if the key field is to be generated by the db
	 */
	public boolean keyIsGenerated;
	/**
	 * meta data for the child form. null if 
	 */
	public ChildDbMetaData[] childMeta;
}


